### ISSUE TITLE
Using Hidden Lake with LoRa Networks

### ISSUE THREAD

**Issue by watashiwa-toki** [number571/go-peer#17]
Is it possible to use Hidden Lake over LoRa networks, especially Meshtastic? If yes, provide some examples, please.

**Comment by number571** [comment]
Thank you for your interest in the project, regarding the question - yes, it is possible. As far as I know, the boards mainly use Bluetooth so that smartphones or computers can broadcast all traffic through it. Thus, in order for Hidden Lake to work on top of LoRa/Meshtastic, it will be necessary to write an adapter (HLA), which will consist of two services - sending and receiving data via Bluetooth. As soon as this write/read capability appears, the subsequent integration with HIdden Lake will be quite simple - using the usual HTTP protocol.
As an example, you can see the implementation of the adapter for the centralized [chatingar](https://chatingar.com/) service in the directory [cmd/hidden_lake/adapters](https://github.com/number571/go-peer/tree/master/cmd/hidden_lake/adapters). In this implementation, the Hidden Lake network adapted to the API of a third-party service and implanted its traffic into it.
