### ISSUE TITLE
An attacker can partially decrypt data

### ISSUE THREAD

**Issue by cpud36** [number571/go-peer#6]
I am going to outline an attack to decrypt some blocks of data using network key. The attack is at `network` package and `network/conn` part in particular.

# Decrypt message len 

The idea is to connect to a node and send some ciphertext to it. The node expects the following:
```
len(P)||len(V)||P||V
```
It first read both len(P) and len(V), and then it expects L=len(P)+len(V) bytes.

If we send <L bytes the node is going to timeout and subsequently reset the connection. If send at least L bytes that are not valid ciphertext, we would immediately get a connection reset.

So the approach is simple:
1. Select 4 blocks of data and save it to X. This will be our len(P)||len(V).
2. Choose n as a guess for L.
3. Send X and then n random bytes. 
4. If we get immediate conn reset, then n >= L.
5. Otherwise n < L.
6. Repeat, until found.

This setup only gets us L. But we still don't know neither of len(P), nor len(V). The following is going to overcome this problem.

# Decrypting Len(V)

Suppose we somehow capture a single encrypted message. That is: `len(P)||len(V)||P||V`.

The idea is that if we perturb V, decryption will still pass, but if we change P, it will fail.

So we can randomly perturb blocks and check wether we get a connection reset.

This will give us both ciphertext and plaintext of a particular `len(V)`.

Then we can attach this `len(V)` block to a given `len(P)` block and decrypt len(P) via algo from previous section.

-----

TL;DR; use TLS, AEAD, AES-GCM and ephemeral keys for transport layer security

**Comment by number571** [comment]
> Decrypt message len

As far as I understood correctly, this section boils down to the problem that we have len(P)||len(V), but there is no information about P||V. Using random bytes as a replacement for P||V, we get the true size of P||V. This attack is indeed possible, but in the developed threat model, by default, it is assumed that the observer knows the entire transmitted block = len(P)||len(V)||P||V. He also knows the distinction between len(P) and len(V) among themselves, because these blocks always have a static size. Therefore, the observer also knows the block size L = P||V.

> Decrypting Len(V)

This is a really interesting kind of attack. This case can indeed be fixed using the algorithms/protocols described above, but it is enough only to take into account all the bytes transmitted, which can be done in the form of a separate header block in the form of an encrypted hash. In this case, changing any byte from the true text or an empty one will lead to a hash mismatch and, as a result, to a connection break.

The fix for this case is in commit https://github.com/number571/go-peer/commit/5b783b2449839ba2374427ed13a0e5b57db44c27.

**Comment by cpud36** [comment]
The section "Decrypt message len" is a bit scarier than just decrypting message length.

E.g. if any transmitted message contains a block with a lot of leading zeros, we can decrypt it.

Let C be the ciphertext of the block in question, and G be previous block of ciphertext.
Then use `G||C` instead of `len(P)` bytes. 

Running an attack to decrypt "message len", actually decrypts block C.

**Comment by cpud36** [comment]
By the way, the hash part is easy to sidestep.

Let IV be the iv of the hash part, H be the plaintext of the hash, and C be the ciphertext.

Then C = E(IV) + H. We can compute the hash directly, so we know both H and C. Thus we know E(IV) for some IV.

The sender can choose IV, so we can sign any transmitted bytes

**Comment by number571** [comment]
I don't quite understand the last two attacks you described, can you describe them more accurately either using the code example or the example of the byte sending/receiving algorithm itself?

**Comment by number571** [comment]
In total, the following scheme of all manipulations in network/conn comes out.

Changing VoidBytes to determine the length of the true message size leads to two problems: 1) Determine the true MsgBytes message with the result of HMAC; 2) Decrypt EncHash.

![Untitled Diagram drawio(31)](https://github.com/number571/go-peer/assets/31502293/fb49e82d-def3-4852-bbe9-be3fb1499c68)

**Comment by cpud36** [comment]
I'll give details about the attack on with Len decryption. For the moment, consider we have a message with a known voidLen. One message is enough to decrypt all other messages.

```
def extract_decryptor(message, voidlen):
  encmsglen, encvoidlen, *_ = message
  return encvoidlen, voidlen

dc = extract_decryptor(THE_MESSAGE, THE_MSG_VLEN)

def try_decrypt(message, i):
  block = message[i]
  prev = message[i-1]
  fake_enclen = concat(prev, block)
  void, voidlen = dc
  fake_header = concat(fake_enclen, void)
  plaintext = try_determine_len(fake_header)
  return plaintext - voidlen

def try_determine_len(header):
  while True:
    select L
    if L is unreasonably large error out
    msg = header with enough bytes
    send msg
    when found L return 
```

The main procedure is try_decrypt, which tries decrypts i-th block of any message. The decryption succeeds if plaintext value of the block is a reasonable message size - in other words plaintext has at least 10 leading zeros.

This is the main issue

**Comment by cpud36** [comment]
I haven't yet looked into your new hashing scheme, but I'll explain the with hash sidestep for the previous scheme.

Consider, for the moment, that hash output is 128 bits.
```
def extract_signer(message):
  msglen, voidlen, h, data = message
  iv, enchash = h
  hash = sha256(data)
  eiv = xor(enchash, hash)
  return iv, eiv

def sign(signer, data):
  hash = sha256(data)
  iv, eiv = signer
  enchash = xor(eiv, hash)
  return concat(iv, enchash)

def determine_msglen(message)
  signer = extract_signer(message)
  while not guessed:
    change message
    message.hash = sign(singer, message.data)
    try send message
```

That is, an attacker does not need to decrypt the hash. One can easily construct a signing device

**Comment by cpud36** [comment]
Actually the new scheme is still vulnerable: you can twiggle voidlen and learn a bit at a time.

If we flip a bit in ciphertext, the corresponding bit is flipped in plaintext too.

The attacker can flip a bit in voidlen block and send modified message. There are two cases:
- the bit is 0, then the new voidlen is larger and send exits with timeout
- the bit is 1, then the new voidlen is smaller and mac verification fails

The visible behaviour is distinguishable, so an attacker learns exact value of given bit.

**Comment by number571** [comment]
The latter case will be difficult to consider as any kind of attack, since the attacker faces the problem of blind brute force. By changing the ciphertext, he can only guess, but this complexity will tend to 2^128 (in terms of block size criteria). This, of course, does not negate the fact that it can intercept, but it cannot effectively choose between states, as you described earlier when calculating the length of encrypted data based only on len blocks. Each new bit change will lead to an unpredictable result.

An attack with a hash (extract_signer) is something on the level of fiction. You have described this algorithm in detail and I have attached the source code on Go to it, which fully reflects the essence of the above algorithm. Maybe I didn't fully understand what the point was here. If you have time, can you specify where exactly in this code the inaccuracy is? Plus, if the attack was really possible earlier, then now it is unlikely to be feasible due to the transfer of sha256 to hmac-sha256.

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/number571/go-peer/pkg/crypto/hashing"
	"github.com/number571/go-peer/pkg/crypto/keybuilder"
	"github.com/number571/go-peer/pkg/crypto/symmetric"
)

const (
	networkKey = "example"
)

type message struct {
	// msglen  []byte
	// voidlen []byte
	enchash []byte
	data    []byte
}

type signer struct {
	iv  []byte
	eiv []byte
}

func main() {
	msg1 := newMessage("1")
	msg2 := newMessage("2")

	signer := extractSigner(msg1)

	msg1.enchash = sign(signer, msg1.data) // the same message
	fmt.Println(hashIsValid(msg1)) // true

	msg2.enchash = sign(signer, msg2.data) // another message
	fmt.Println(hashIsValid(msg2)) // false
}

func hashIsValid(message *message) bool {
	cipher := newCipher()
	hash := cipher.DecryptBytes(message.enchash)

	hashBytes := hashing.NewSHA256Hasher(message.data).ToBytes()
	return bytes.Equal(hash, hashBytes)
}

func newMessage(msgStr string) *message {
	cipher := newCipher()

	encMsgBytes := cipher.EncryptBytes([]byte(msgStr))
	voidBytes := []byte("abcdefghijk")

	rawData := bytes.Join(
		[][]byte{
			encMsgBytes,
			voidBytes,
		},
		[]byte{},
	)
	hashBytes := hashing.NewSHA256Hasher(rawData).ToBytes()

	encHashBytes := cipher.EncryptBytes(hashBytes)
	return &message{
		enchash: encHashBytes,
		data:    rawData,
	}
}

func extractSigner(message *message) *signer {
	hash := hashing.NewSHA256Hasher(message.data).ToBytes()
	eiv := xorBytes(message.enchash[symmetric.CAESBlockSize:], hash)
	return &signer{
		iv:  message.enchash[:symmetric.CAESBlockSize],
		eiv: eiv,
	}
}

func sign(signer *signer, data []byte) []byte {
	hash := hashing.NewSHA256Hasher(data).ToBytes()
	enchash := xorBytes(signer.eiv, hash)
	return bytes.Join(
		[][]byte{
			signer.iv,
			enchash,
		},
		[]byte{},
	)
}

func xorBytes(x, y []byte) []byte {
	if len(x) != len(y) {
		panic("len x != len y")
	}
	result := make([]byte, 0, len(x))
	for i := range x {
		result = append(result, x[i]^y[i])
	}
	return result
}

func newCipher() symmetric.ICipher {
	keyBuilder := keybuilder.NewKeyBuilder(1, []byte("salt"))
	encryptKey := keyBuilder.Build(networkKey)
	return symmetric.NewAESCipher(encryptKey)
}

```

The attack with extract_decryptor is described extremely abstractly and with errors in the code itself. I tried to understand the basic meaning of the algorithm, but most likely I couldn't. My assumption is that you take a static value for voidLen, which is not true. The size of void bytes is random. But most likely I did not understand the main point, including with 10 zero bytes.

I also edited the scheme, changed the separate encryption of the hmac length and result blocks. Combined all these components into one iteration of encryption. The general scheme began to look simpler. Removed hmac from plaintext. Now it hashes only raw encrypted bytes with void bytes.

![Untitled Diagram drawio(33)(1)](https://github.com/number571/go-peer/assets/31502293/ee48d650-c00a-4211-849b-49a983c4e188)
